name: CI - Lint, Test, Train

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Run Black (check only)
        run: |
          black --check src/ tests/

      - name: Run isort (check only)
        run: |
          isort --check-only src/ tests/

      - name: Run flake8
        run: |
          flake8 src/ tests/

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Train model for tests
        run: |
          python src/train.py --output-dir models

      - name: Run pytest
        run: |
          pytest tests/ -v --cov=src --cov-report=term --cov-report=xml

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: always()
        with:
          files: ./coverage.xml
          fail_ci_if_error: false

  train:
    name: Train Model
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train model
        run: |
          python src/train.py --output-dir models

      - name: Display metrics
        run: |
          cat models/metrics.json

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            models/
          retention-days: 30

      - name: Upload training metrics
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: models/metrics.json
          retention-days: 90

